<a href="https://colab.research.google.com/github/izzettekbas/AI7000_Projects/blob/main/Guided_project_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chapter 3: Data cleaning exercise

### Sales department performance analysis

The HR department wants to analyze the performance of the employees in the sales department.

### Data Reading
Rachel wrote a text file employee_revenue.txt including all necessary information, but she needs help to extract the necessary information.

Start by uploading the employee_revenue file to the working directory.

📌 Use the .read() method to open the text file in read mode and assign it to the variable "data".


In [81]:
#Open the file in read mode
file = open("/content/employee_revenue.txt", "r")
data = file.read()

In [82]:
"""
from google.colab import drive
drive.mount('/content/drive')
"""

"\nfrom google.colab import drive\ndrive.mount('/content/drive')\n"

In [83]:
#Print the data
print(data)

  Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.  
omer called 10 times and Sold 2 courses generated 60 dollars last month with a 6$ average deal size.
   KAren called 500 people and achieved success by GETting 24$ average deal size, got 12000 dollars revenue.     
Celine with 70 calls, made 2275 dollars and 32$ average deal size IN the previous month.  
     Sue called 100 people and earned 500 Dollars in REvenue and an AVERAGE DEAL SIZE of 5$ Last month.
Bora called 100 people generated 770 dollars last month, his average deal size was 25$.  
Rose made 600 phone calls and GENERATING 4000 dollars a past month 25$ average deal SIZE. 
Ellen made 800 calls and generated 6000 dollars a prior mONTH and reached 40$ the average deal size. 
 bob made 200 phone calls, helped to make a proGress and generated 800 dollars LAST MONTH and gaining 15$ average deal size.
Taylor, with 450 calls generated 1200 dollars in revenue pASt month, and the average deal s

### Data Cleaning

You can see that the data needs to be cleaned and information has to be extracted from these lines.

To be able to clean the data, you need to separate the text into lines.

📌 Use the .splitlines() method.

In [84]:
#Seperate the data into lines
lines = data.splitlines()
print(lines)

['  Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.  ', 'omer called 10 times and Sold 2 courses generated 60 dollars last month with a 6$ average deal size.', '   KAren called 500 people and achieved success by GETting 24$ average deal size, got 12000 dollars revenue.     ', 'Celine with 70 calls, made 2275 dollars and 32$ average deal size IN the previous month.  ', '     Sue called 100 people and earned 500 Dollars in REvenue and an AVERAGE DEAL SIZE of 5$ Last month.', 'Bora called 100 people generated 770 dollars last month, his average deal size was 25$.  ', 'Rose made 600 phone calls and GENERATING 4000 dollars a past month 25$ average deal SIZE. ', 'Ellen made 800 calls and generated 6000 dollars a prior mONTH and reached 40$ the average deal size. ', ' bob made 200 phone calls, helped to make a proGress and generated 800 dollars LAST MONTH and gaining 15$ average deal size.', 'Taylor, with 450 calls generated 1200 dollars in revenue pASt 

### Clean the data line by line

Start to clean the data for the first line.

📌 Use the .strip() method to remove the whitespaces from the edges of the string.

In [85]:
#Take the first line
string = lines[0]
print(string)

  Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.  


In [86]:
#Remove the whitespaces from the edges
string = string.strip()
print(string)

Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.


Next, you need to fix the capitalization issues.

📌 Use the .lower() method to convert the text to lowercase.

📌 Then use the .capitalize() method to capitalize the first letter.

In [87]:
#Convert the string to lowercase
string = string.lower()
string

'ben made 300 calls and generated 2400 dollars last month with an 8$ average deal size.'

In [88]:
#Capitalize the first character
string = string.capitalize()
string

'Ben made 300 calls and generated 2400 dollars last month with an 8$ average deal size.'

### Information Extraction

To extract the information, you need to split the sentence into words.

📌 Use the .split() method.


In [89]:
#Split the sentece into words
split_string = string.split()
split_string

['Ben',
 'made',
 '300',
 'calls',
 'and',
 'generated',
 '2400',
 'dollars',
 'last',
 'month',
 'with',
 'an',
 '8$',
 'average',
 'deal',
 'size.']

You might noticed that the first element in the list is the name and the third element is the number of calls.

📌 Use the indeces to extract the name and number of calls.

In [90]:
#Use the index 0 to access the name element
name = split_string[0]
name

'Ben'

In [91]:
#Use the index 2 to access the number of calls element
call_number = split_string[2]
call_number

'300'

So far so good!

But as you can see the sentence order is not the same after the 7th element.

To extract the average deal size you need to come up with a different approach. You can use the "$" sign to find the corresponding element.

📌 Loop over the list to find the element that includes the "$" sign.

📌 Then, use the .split() method to divide the string into the number and the $ sign.

In [92]:
#Find the element with the "$" sign
for i in split_string:
  #Divide the number from it
  if '$' in i:
    average_deal_size = i.split('$')[0]
#Print the average deal size
average_deal_size

'8'

Similarly, we can use the string "dollars" to extract the revenue, which is the element right before "dollars".

📌 Use the .index() method to identify the index for the "dollars" element.

📌 Then, use this index to specify and extract the revenue.

In [93]:
#Find the index of element "dollars"
dollars_index = split_string.index("dollars")
dollars_index

7

In [94]:
#Subtract one from the index to identify the index of the revenue element
revenue_index = dollars_index - 1
revenue_index

6

In [95]:
#Extract the revenue
revenue = split_string[revenue_index]
revenue

'2400'

Great! You extracted all necessary information.

📌 Print the information and check the types of the data.

In [96]:
#Print out the extracted information
print("Name:", name)
print("Number of calls:", call_number)
print("Average deal size:", average_deal_size)
print("Revenue:", revenue)

Name: Ben
Number of calls: 300
Average deal size: 8
Revenue: 2400


In [97]:
#Check the types
print("Name:", type(name))
print("Number of calls:", type(call_number))
print("Average deal size:", type(average_deal_size))
print("Revenue:", type(revenue))

Name: <class 'str'>
Number of calls: <class 'str'>
Average deal size: <class 'str'>
Revenue: <class 'str'>


As you can see, we have the type string for all the data, but the average deal size, number of calls, and the revenue need to be integers.

📌 Convert the data using the int() function and check again.

In [98]:
#Convert the datatypes of average deal size, number of calls, and revenue
call_number = int(call_number)
average_deal_size = int(average_deal_size)
revenue = int(revenue)

In [99]:
#Print out the information again
print("Name:", type(name))
print("Number of calls:", type(call_number))
print("Average deal size:", type(average_deal_size))
print("Revenue:", type(revenue))

Name: <class 'str'>
Number of calls: <class 'int'>
Average deal size: <class 'int'>
Revenue: <class 'int'>


Now, you need to apply all the methods and functions to the list that contains the different strings of all employees.

📌 Create an empty lists for storing names, number of calls, average deal sizes, and revenues.

📌 Use a for loop to iterate through the list with the whole data.

📌 Print out the necessary information.

In [100]:
#Create empty lists for the names, number of calls, average deal sizes, revenues
names = []
call_numbers = []
average_deal_sizes = []
revenues = []

In [101]:
#Loop over the whole data
for employee in lines:
    #Clean the string
    employee = employee.strip()
    employee = employee.lower()
    employee = employee.capitalize()

    #Split the clean string
    split_employee = employee.split()

    #Extract the name and call number
    name = split_employee[0]
    call_number = split_employee[2]

    #Extract the average deal size
    for i in split_employee:
      if '$' in i:
        average_deal_size = i.split('$')[0]

    #Extract the revenue
    dollars_index = split_employee.index("dollars")
    revenue_index = dollars_index - 1
    revenue = split_employee[revenue_index]

    #Convert to the correct data types
    call_number = int(call_number)
    average_deal_size = int(average_deal_size)
    revenue = int(revenue)

    #Append the information to the lists
    names.append(name)
    call_numbers.append(call_number)
    average_deal_sizes.append(average_deal_size)
    revenues.append(revenue)

#Print out the information
print(f"Names: {names}")
print(f"Number of calls: {call_numbers}")
print(f"Average deal sizes: {average_deal_sizes}")
print(f"Revenues: {revenues}")

Names: ['Ben', 'Omer', 'Karen', 'Celine', 'Sue', 'Bora', 'Rose', 'Ellen', 'Bob', 'Taylor,', 'Jude']
Number of calls: [300, 10, 500, 70, 100, 100, 600, 800, 200, 450, 80]
Average deal sizes: [8, 6, 24, 32, 5, 25, 25, 40, 15, 10, 12]
Revenues: [2400, 60, 12000, 2275, 500, 770, 4000, 6000, 800, 1200, 500]


Finally, you can make the process even easier and reusable by defining functions.

📌 Define the function "clean_extract".

📌 Use the retured values by assigning them to variables.

In [102]:
#Create empty lists again
names = []
call_numbers = []
average_deal_sizes = []
revenues = []

In [103]:
#Define a function to clean and extract the data
def clean_extract(lines):
  for employee in lines:
    #Clean the string
    employee = employee.strip()
    employee = employee.lower()
    employee = employee.capitalize()

    #Split the clean string
    split_employee = employee.split()

    #Extract the name and call number
    name = split_employee[0]
    call_number = split_employee[2]

    #Extract the average deal size
    for i in split_employee:
      if '$' in i:
        average_deal_size = i.split('$')[0]

    #Extract the revenue
    dollars_index = split_employee.index("dollars")
    revenue_index = dollars_index - 1
    revenue = split_employee[revenue_index]

    #Convert to the correct data types
    call_number = int(call_number)
    average_deal_size = int(average_deal_size)
    revenue = int(revenue)

    #Append the information to the lists
    names.append(name)
    call_numbers.append(call_number)
    average_deal_sizes.append(average_deal_size)
    revenues.append(revenue)
  return names, call_numbers, average_deal_sizes, revenues

In [104]:
#Assign returned values to variables
names, call_numbers, average_deal_sizes, revenues = clean_extract(lines)

In [105]:
#Print out the information
print(f"Names: {names}")
print(f"Number of calls: {call_numbers}")
print(f"Average deal sizes: {average_deal_sizes}")
print(f"Revenues: {revenues}")

Names: ['Ben', 'Omer', 'Karen', 'Celine', 'Sue', 'Bora', 'Rose', 'Ellen', 'Bob', 'Taylor,', 'Jude']
Number of calls: [300, 10, 500, 70, 100, 100, 600, 800, 200, 450, 80]
Average deal sizes: [8, 6, 24, 32, 5, 25, 25, 40, 15, 10, 12]
Revenues: [2400, 60, 12000, 2275, 500, 770, 4000, 6000, 800, 1200, 500]


### Performance Analysis Report

Now that you cleaned the string and extracted all the information using the function, you can create performance analysis report for the last month.

📌 Assign IDs to each employee.

📌 Create dictionaries.

📌 Sort the dictionaries.




First, check how many employees there are and assign the IDs.

📌 Use the len() and range() function.


In [106]:
#Check the number of employees
print(len(names))

11


In [107]:
#Generate IDs
IDs = list(range(len(names)))
IDs

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [108]:
#Check the number of IDs
len(IDs)

11

With the IDs ready, you need to assign the IDs to the employees.

📌 Use the zip() function to pair the employee with the ID.

📌 Convert the zip object into a dictionary.

In [109]:
#Pair the names with the IDs in a dictionary
dictionary1 = dict(zip(IDs, names))
dictionary1

{0: 'Ben',
 1: 'Omer',
 2: 'Karen',
 3: 'Celine',
 4: 'Sue',
 5: 'Bora',
 6: 'Rose',
 7: 'Ellen',
 8: 'Bob',
 9: 'Taylor,',
 10: 'Jude'}

Similarly, create a dictionary for the  employees and their revenues.

In [110]:
#Pair the names with the revenues
dictionary2 = dict(zip(revenues, names))
dictionary2


{2400: 'Ben',
 60: 'Omer',
 12000: 'Karen',
 2275: 'Celine',
 500: 'Jude',
 770: 'Bora',
 4000: 'Rose',
 6000: 'Ellen',
 800: 'Bob',
 1200: 'Taylor,'}

Finally, you need to find the employees with the best and lowest performance.

📌 Sort the dictionary using the sorted() function in ascending and descending order.


In [111]:
#Find the lowest performing employees (ascending order)
sorted_dictionary = sorted(dictionary2)[0:3]

for i in sorted_dictionary:
  print(dictionary2[i])

Omer
Jude
Bora


In [112]:
#Find the best performing employees (descending order)
sorted_dictionary2 = sorted(dictionary2, reverse = True)[0:3]

for i in sorted_dictionary2:
  print(dictionary2[i])

Karen
Ellen
Rose


##NumPy

Rachel is very happy with the way you cleaned and structured the employee data last time, but she wants to take things one step further. The sales team wants to track the performance of the employees not only by the revenue they generated, but also taking the number of calls and the average deal size into account. For that, Rachel wants you to create a software for reporting. To be able to perform calculations on the data you decide that creating a data structure using Numpy will be best.

### Importing NumPy

You plan to create a data structure using NumPy.

📌 Import the NumPy library as.

In [113]:
#Import the NumPy library
import numpy as np

###Creating an initial (base) arrays

Next, you need to prepare an array in which you will store the values. The initial array will be empty. Since it will hold numerical data, the data type should be integer.

📌 Create an empty array using .array().

📌 Use the *dtype* parameter to specify the data type.

In [114]:
#Create an empty array with the data type integer
datanp = np.array([], dtype = int)

###Functions to add the data

Now that your empty array is ready, you need to transfer the data from the lists to the array. You create 2 functions functions for this.

1. append_names function: A function that takes the "names" list and adds the index of each name to the "data" array.

  📌 Use a for loop and the .append() method for the indexes.

2. append_performance_measures function: A function that takes one of the remaining lists to add the sales performance data like number of calls, average deal size and revenue to the "data" array.

  📌 Use the .append() method.

In [115]:
#Define the append_names function
def append_names(names_list):
  global datanp
  for i in names_list:
    datanp = np.append(datanp, names_list.index(i))

In [116]:
#Define the append_performance_measures function
def append_performance_measures(features_list):
  global datanp
  datanp = np.append(datanp, features_list)

Call the functions to add the data to the array and print the array and its shape to see the result.

📌 Use the .shape() method.

In [117]:
#Use the append_names and append_sales_performance_measures to add the data
append_names(names)
append_performance_measures(call_numbers)
append_performance_measures(average_deal_sizes)
append_performance_measures(revenues)

#Print the array and its shape to see the result
print(datanp)
print(datanp.shape)

[    0     1     2     3     4     5     6     7     8     9    10   300
    10   500    70   100   100   600   800   200   450    80     8     6
    24    32     5    25    25    40    15    10    12  2400    60 12000
  2275   500   770  4000  6000   800  1200   500]
(44,)


###Reshape the array

But like this, your array is not very structured. You need a 2D-array to be able to work better with it. The original data was 4 lists each with 11 values. So, the "data" array should have 4 rows and 11 columns. Print the result afterwards.

📌 Use the .reshape() method to rearrange the values in the array.

In [118]:
#Use the .reshape() method to change the array structure to 4 rows and 11 columns
datanp = datanp.reshape(4,11)

#Print the resulting array and its shape
print(datanp)
print(datanp.shape)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]]
(4, 11)


###Accessing values

Inside the array you can access the values in different ways.

1. Print each row separately.

  📌 Write down the array name and the index of the row you want to access.

In [119]:
#Print the name indexes
print(datanp[0])

[ 0  1  2  3  4  5  6  7  8  9 10]


In [120]:
#Print the number of calls
print(datanp[1])

[300  10 500  70 100 100 600 800 200 450  80]


In [121]:
#Print the average deal sizes
print(datanp[2])

[ 8  6 24 32  5 25 25 40 15 10 12]


In [122]:
#Print the revenues
print(datanp[3])

[ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]


2. Print a specific value.

  📌 Give the index of the row and the column of the value you want to access.
  For example, to get the revenue generated by Ellen, specify the value in the 3rd row and 7th column.

In [123]:
#Print the revenue generated by Ellen
print(datanp[3,7])

6000


###Analyzing the data

Great, your array is ready!

The sales team has a formula that they use to calculate the performance score of an employee.


\begin{align}
        \text{Performance} = \frac{\text{Average deal size x Revenue}}{\text{Number of calls}}
    \end{align}


📌 Create a function called “calculate_performance” to implement this formula. It should take the employee name as an input.

In [124]:
#Define the function calculate_performance
def calculate_performance(employee_name):
  global names, datanp
  idx = names.index(employee_name)
  call_number = datanp[1,idx]
  avg_deal_size = datanp[2,idx]
  revenue = datanp[3,idx]

  score = (avg_deal_size * revenue) / call_number

  return score

###Try it out

Let's check Ellen's performance score and print the result.

In [125]:
#Use the calculate performance function to print Ellen's performance
calculate_performance("Ellen")

300.0

###Calculate the performance of each employee
Now you need to calculate the performance score of each employee and add these scores to a list.

📌 Create an empty list "performance_scores" to hold the scores.

📌 Use a for loop to convert the scores into integer type data and append it to the list "sperformance_scores".

In [126]:
#Calculate the performance of each employee
performance_scores = []
for i in names:
  score = int(calculate_performance(i))
  performance_scores.append(score)

print(performance_scores)

[64, 36, 576, 1040, 25, 192, 166, 300, 60, 26, 75]


###Add the scores to the "data" array

Next, you need to add the scores to your "data" array and print the result.

📌 Use the .concatenate() method to add the "performance_scores" list to the "data" array.

In [127]:
#Add the "performance_scores" list to the "data" array
datanp = np.concatenate((datanp, [performance_scores]), axis = 0)

#Print the resulting array
print(datanp)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]
 [   64    36   576  1040    25   192   166   300    60    26    75]]


###Find out the best and worst performing employees

Finally, you need to determine the best and worst performing employees.

📌 Use the .argmax() and .argmin() methods to find the index of the best and worst performing employees.

In [129]:
#Use .argmax() and .argmin() methods to determine the best and worst performing employees
idx_best_employee = np.argmax(datanp[4])
idx_worst_employee = np.argmin(datanp[4])

#Print out the results
print(f"Best Performing Employee: {names[idx_best_employee]}")
print(f"Worst Performing Employee: {names[idx_worst_employee]}")

Best Performing Employee: Celine
Worst Performing Employee: Sue


##Pandas
The sales department wants to compare the performances of this and last year. Firstly, they delivered your team the performance review from last year. The data is in a comma-separated format, a .csv file called “employee_revenue_lastyear.csv”. It is in tabular form and includes information about 11 employees.