<a href="https://colab.research.google.com/github/izzettekbas/AI7000_Projects/blob/main/Guided_project_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Chapter 3: Data cleaning exercise

### Sales department performance analysis

The HR department wants to analyze the performance of the employees in the sales department.

### Data Reading
Rachel wrote a text file employee_revenue.txt including all necessary information, but she needs help to extract the necessary information.

Start by uploading the employee_revenue file to the working directory.

📌 Use the .read() method to open the text file in read mode and assign it to the variable "data".


In [153]:
#Open the file in read mode
file = open("/content/employee_revenue.txt", "r")
data = file.read()

In [154]:
"""
from google.colab import drive
drive.mount('/content/drive')
"""

"\nfrom google.colab import drive\ndrive.mount('/content/drive')\n"

In [155]:
#Print the data
print(data)

  Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.  
omer called 10 times and Sold 2 courses generated 60 dollars last month with a 6$ average deal size.
   KAren called 500 people and achieved success by GETting 24$ average deal size, got 12000 dollars revenue.     
Celine with 70 calls, made 2275 dollars and 32$ average deal size IN the previous month.  
     Sue called 100 people and earned 500 Dollars in REvenue and an AVERAGE DEAL SIZE of 5$ Last month.
Bora called 100 people generated 770 dollars last month, his average deal size was 25$.  
Rose made 600 phone calls and GENERATING 4000 dollars a past month 25$ average deal SIZE. 
Ellen made 800 calls and generated 6000 dollars a prior mONTH and reached 40$ the average deal size. 
 bob made 200 phone calls, helped to make a proGress and generated 800 dollars LAST MONTH and gaining 15$ average deal size.
Taylor, with 450 calls generated 1200 dollars in revenue pASt month, and the average deal s

### Data Cleaning

You can see that the data needs to be cleaned and information has to be extracted from these lines.

To be able to clean the data, you need to separate the text into lines.

📌 Use the .splitlines() method.

In [156]:
#Seperate the data into lines
lines = data.splitlines()
print(lines)

['  Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.  ', 'omer called 10 times and Sold 2 courses generated 60 dollars last month with a 6$ average deal size.', '   KAren called 500 people and achieved success by GETting 24$ average deal size, got 12000 dollars revenue.     ', 'Celine with 70 calls, made 2275 dollars and 32$ average deal size IN the previous month.  ', '     Sue called 100 people and earned 500 Dollars in REvenue and an AVERAGE DEAL SIZE of 5$ Last month.', 'Bora called 100 people generated 770 dollars last month, his average deal size was 25$.  ', 'Rose made 600 phone calls and GENERATING 4000 dollars a past month 25$ average deal SIZE. ', 'Ellen made 800 calls and generated 6000 dollars a prior mONTH and reached 40$ the average deal size. ', ' bob made 200 phone calls, helped to make a proGress and generated 800 dollars LAST MONTH and gaining 15$ average deal size.', 'Taylor, with 450 calls generated 1200 dollars in revenue pASt 

### Clean the data line by line

Start to clean the data for the first line.

📌 Use the .strip() method to remove the whitespaces from the edges of the string.

In [157]:
#Take the first line
string = lines[0]
print(string)

  Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.  


In [158]:
#Remove the whitespaces from the edges
string = string.strip()
print(string)

Ben made 300 calls and generated 2400 dollars last Month with an 8$ average deal size.


Next, you need to fix the capitalization issues.

📌 Use the .lower() method to convert the text to lowercase.

📌 Then use the .capitalize() method to capitalize the first letter.

In [159]:
#Convert the string to lowercase
string = string.lower()
string

'ben made 300 calls and generated 2400 dollars last month with an 8$ average deal size.'

In [160]:
#Capitalize the first character
string = string.capitalize()
string

'Ben made 300 calls and generated 2400 dollars last month with an 8$ average deal size.'

### Information Extraction

To extract the information, you need to split the sentence into words.

📌 Use the .split() method.


In [161]:
#Split the sentece into words
split_string = string.split()
split_string

['Ben',
 'made',
 '300',
 'calls',
 'and',
 'generated',
 '2400',
 'dollars',
 'last',
 'month',
 'with',
 'an',
 '8$',
 'average',
 'deal',
 'size.']

You might noticed that the first element in the list is the name and the third element is the number of calls.

📌 Use the indeces to extract the name and number of calls.

In [162]:
#Use the index 0 to access the name element
name = split_string[0]
name

'Ben'

In [163]:
#Use the index 2 to access the number of calls element
call_number = split_string[2]
call_number

'300'

So far so good!

But as you can see the sentence order is not the same after the 7th element.

To extract the average deal size you need to come up with a different approach. You can use the "$" sign to find the corresponding element.

📌 Loop over the list to find the element that includes the "$" sign.

📌 Then, use the .split() method to divide the string into the number and the $ sign.

In [164]:
#Find the element with the "$" sign
for i in split_string:
  #Divide the number from it
  if '$' in i:
    average_deal_size = i.split('$')[0]
#Print the average deal size
average_deal_size

'8'

Similarly, we can use the string "dollars" to extract the revenue, which is the element right before "dollars".

📌 Use the .index() method to identify the index for the "dollars" element.

📌 Then, use this index to specify and extract the revenue.

In [165]:
#Find the index of element "dollars"
dollars_index = split_string.index("dollars")
dollars_index

7

In [166]:
#Subtract one from the index to identify the index of the revenue element
revenue_index = dollars_index - 1
revenue_index

6

In [167]:
#Extract the revenue
revenue = split_string[revenue_index]
revenue

'2400'

Great! You extracted all necessary information.

📌 Print the information and check the types of the data.

In [168]:
#Print out the extracted information
print("Name:", name)
print("Number of calls:", call_number)
print("Average deal size:", average_deal_size)
print("Revenue:", revenue)

Name: Ben
Number of calls: 300
Average deal size: 8
Revenue: 2400


In [169]:
#Check the types
print("Name:", type(name))
print("Number of calls:", type(call_number))
print("Average deal size:", type(average_deal_size))
print("Revenue:", type(revenue))

Name: <class 'str'>
Number of calls: <class 'str'>
Average deal size: <class 'str'>
Revenue: <class 'str'>


As you can see, we have the type string for all the data, but the average deal size, number of calls, and the revenue need to be integers.

📌 Convert the data using the int() function and check again.

In [170]:
#Convert the datatypes of average deal size, number of calls, and revenue
call_number = int(call_number)
average_deal_size = int(average_deal_size)
revenue = int(revenue)

In [171]:
#Print out the information again
print("Name:", type(name))
print("Number of calls:", type(call_number))
print("Average deal size:", type(average_deal_size))
print("Revenue:", type(revenue))

Name: <class 'str'>
Number of calls: <class 'int'>
Average deal size: <class 'int'>
Revenue: <class 'int'>


Now, you need to apply all the methods and functions to the list that contains the different strings of all employees.

📌 Create an empty lists for storing names, number of calls, average deal sizes, and revenues.

📌 Use a for loop to iterate through the list with the whole data.

📌 Print out the necessary information.

In [172]:
#Create empty lists for the names, number of calls, average deal sizes, revenues
names = []
call_numbers = []
average_deal_sizes = []
revenues = []

In [173]:
#Loop over the whole data
for employee in lines:
    #Clean the string
    employee = employee.strip()
    employee = employee.lower()
    employee = employee.capitalize()

    #Split the clean string
    split_employee = employee.split()

    #Extract the name and call number
    name = split_employee[0]
    call_number = split_employee[2]

    #Extract the average deal size
    for i in split_employee:
      if '$' in i:
        average_deal_size = i.split('$')[0]

    #Extract the revenue
    dollars_index = split_employee.index("dollars")
    revenue_index = dollars_index - 1
    revenue = split_employee[revenue_index]

    #Convert to the correct data types
    call_number = int(call_number)
    average_deal_size = int(average_deal_size)
    revenue = int(revenue)

    #Append the information to the lists
    names.append(name)
    call_numbers.append(call_number)
    average_deal_sizes.append(average_deal_size)
    revenues.append(revenue)

#Print out the information
print(f"Names: {names}")
print(f"Number of calls: {call_numbers}")
print(f"Average deal sizes: {average_deal_sizes}")
print(f"Revenues: {revenues}")

Names: ['Ben', 'Omer', 'Karen', 'Celine', 'Sue', 'Bora', 'Rose', 'Ellen', 'Bob', 'Taylor,', 'Jude']
Number of calls: [300, 10, 500, 70, 100, 100, 600, 800, 200, 450, 80]
Average deal sizes: [8, 6, 24, 32, 5, 25, 25, 40, 15, 10, 12]
Revenues: [2400, 60, 12000, 2275, 500, 770, 4000, 6000, 800, 1200, 500]


Finally, you can make the process even easier and reusable by defining functions.

📌 Define the function "clean_extract".

📌 Use the retured values by assigning them to variables.

In [174]:
#Create empty lists again
names = []
call_numbers = []
average_deal_sizes = []
revenues = []

In [175]:
#Define a function to clean and extract the data
def clean_extract(lines):
  for employee in lines:
    #Clean the string
    employee = employee.strip()
    employee = employee.lower()
    employee = employee.capitalize()

    #Split the clean string
    split_employee = employee.split()

    #Extract the name and call number
    name = split_employee[0]
    call_number = split_employee[2]

    #Extract the average deal size
    for i in split_employee:
      if '$' in i:
        average_deal_size = i.split('$')[0]

    #Extract the revenue
    dollars_index = split_employee.index("dollars")
    revenue_index = dollars_index - 1
    revenue = split_employee[revenue_index]

    #Convert to the correct data types
    call_number = int(call_number)
    average_deal_size = int(average_deal_size)
    revenue = int(revenue)

    #Append the information to the lists
    names.append(name)
    call_numbers.append(call_number)
    average_deal_sizes.append(average_deal_size)
    revenues.append(revenue)
  return names, call_numbers, average_deal_sizes, revenues

In [176]:
#Assign returned values to variables
names, call_numbers, average_deal_sizes, revenues = clean_extract(lines)

In [177]:
#Print out the information
print(f"Names: {names}")
print(f"Number of calls: {call_numbers}")
print(f"Average deal sizes: {average_deal_sizes}")
print(f"Revenues: {revenues}")

Names: ['Ben', 'Omer', 'Karen', 'Celine', 'Sue', 'Bora', 'Rose', 'Ellen', 'Bob', 'Taylor,', 'Jude']
Number of calls: [300, 10, 500, 70, 100, 100, 600, 800, 200, 450, 80]
Average deal sizes: [8, 6, 24, 32, 5, 25, 25, 40, 15, 10, 12]
Revenues: [2400, 60, 12000, 2275, 500, 770, 4000, 6000, 800, 1200, 500]


### Performance Analysis Report

Now that you cleaned the string and extracted all the information using the function, you can create performance analysis report for the last month.

📌 Assign IDs to each employee.

📌 Create dictionaries.

📌 Sort the dictionaries.




First, check how many employees there are and assign the IDs.

📌 Use the len() and range() function.


In [178]:
#Check the number of employees
print(len(names))

11


In [179]:
#Generate IDs
IDs = list(range(len(names)))
IDs

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [180]:
#Check the number of IDs
len(IDs)

11

With the IDs ready, you need to assign the IDs to the employees.

📌 Use the zip() function to pair the employee with the ID.

📌 Convert the zip object into a dictionary.

In [181]:
#Pair the names with the IDs in a dictionary
dictionary1 = dict(zip(IDs, names))
dictionary1

{0: 'Ben',
 1: 'Omer',
 2: 'Karen',
 3: 'Celine',
 4: 'Sue',
 5: 'Bora',
 6: 'Rose',
 7: 'Ellen',
 8: 'Bob',
 9: 'Taylor,',
 10: 'Jude'}

Similarly, create a dictionary for the  employees and their revenues.

In [182]:
#Pair the names with the revenues
dictionary2 = dict(zip(revenues, names))
dictionary2


{2400: 'Ben',
 60: 'Omer',
 12000: 'Karen',
 2275: 'Celine',
 500: 'Jude',
 770: 'Bora',
 4000: 'Rose',
 6000: 'Ellen',
 800: 'Bob',
 1200: 'Taylor,'}

Finally, you need to find the employees with the best and lowest performance.

📌 Sort the dictionary using the sorted() function in ascending and descending order.


In [183]:
#Find the lowest performing employees (ascending order)
sorted_dictionary = sorted(dictionary2)[0:3]

for i in sorted_dictionary:
  print(dictionary2[i])

Omer
Jude
Bora


In [184]:
#Find the best performing employees (descending order)
sorted_dictionary2 = sorted(dictionary2, reverse = True)[0:3]

for i in sorted_dictionary2:
  print(dictionary2[i])

Karen
Ellen
Rose


##NumPy

Rachel is very happy with the way you cleaned and structured the employee data last time, but she wants to take things one step further. The sales team wants to track the performance of the employees not only by the revenue they generated, but also taking the number of calls and the average deal size into account. For that, Rachel wants you to create a software for reporting. To be able to perform calculations on the data you decide that creating a data structure using Numpy will be best.

### Importing NumPy

You plan to create a data structure using NumPy.

📌 Import the NumPy library as.

In [185]:
#Import the NumPy library
import numpy as np

###Creating an initial (base) arrays

Next, you need to prepare an array in which you will store the values. The initial array will be empty. Since it will hold numerical data, the data type should be integer.

📌 Create an empty array using .array().

📌 Use the *dtype* parameter to specify the data type.

In [186]:
#Create an empty array with the data type integer
datanp = np.array([], dtype = int)

###Functions to add the data

Now that your empty array is ready, you need to transfer the data from the lists to the array. You create 2 functions functions for this.

1. append_names function: A function that takes the "names" list and adds the index of each name to the "data" array.

  📌 Use a for loop and the .append() method for the indexes.

2. append_performance_measures function: A function that takes one of the remaining lists to add the sales performance data like number of calls, average deal size and revenue to the "data" array.

  📌 Use the .append() method.

In [187]:
#Define the append_names function
def append_names(names_list):
  global datanp
  for i in names_list:
    datanp = np.append(datanp, names_list.index(i))

In [188]:
#Define the append_performance_measures function
def append_performance_measures(features_list):
  global datanp
  datanp = np.append(datanp, features_list)

Call the functions to add the data to the array and print the array and its shape to see the result.

📌 Use the .shape() method.

In [189]:
#Use the append_names and append_sales_performance_measures to add the data
append_names(names)
append_performance_measures(call_numbers)
append_performance_measures(average_deal_sizes)
append_performance_measures(revenues)

#Print the array and its shape to see the result
print(datanp)
print(datanp.shape)

[    0     1     2     3     4     5     6     7     8     9    10   300
    10   500    70   100   100   600   800   200   450    80     8     6
    24    32     5    25    25    40    15    10    12  2400    60 12000
  2275   500   770  4000  6000   800  1200   500]
(44,)


###Reshape the array

But like this, your array is not very structured. You need a 2D-array to be able to work better with it. The original data was 4 lists each with 11 values. So, the "data" array should have 4 rows and 11 columns. Print the result afterwards.

📌 Use the .reshape() method to rearrange the values in the array.

In [190]:
#Use the .reshape() method to change the array structure to 4 rows and 11 columns
datanp = datanp.reshape(4,11)

#Print the resulting array and its shape
print(datanp)
print(datanp.shape)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]]
(4, 11)


###Accessing values

Inside the array you can access the values in different ways.

1. Print each row separately.

  📌 Write down the array name and the index of the row you want to access.

In [191]:
#Print the name indexes
print(datanp[0])

[ 0  1  2  3  4  5  6  7  8  9 10]


In [192]:
#Print the number of calls
print(datanp[1])

[300  10 500  70 100 100 600 800 200 450  80]


In [193]:
#Print the average deal sizes
print(datanp[2])

[ 8  6 24 32  5 25 25 40 15 10 12]


In [194]:
#Print the revenues
print(datanp[3])

[ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]


2. Print a specific value.

  📌 Give the index of the row and the column of the value you want to access.
  For example, to get the revenue generated by Ellen, specify the value in the 3rd row and 7th column.

In [195]:
#Print the revenue generated by Ellen
print(datanp[3,7])

6000


###Analyzing the data

Great, your array is ready!

The sales team has a formula that they use to calculate the performance score of an employee.


\begin{align}
        \text{Performance} = \frac{\text{Average deal size x Revenue}}{\text{Number of calls}}
    \end{align}


📌 Create a function called “calculate_performance” to implement this formula. It should take the employee name as an input.

In [196]:
#Define the function calculate_performance
def calculate_performance(employee_name):
  global names, datanp
  idx = names.index(employee_name)
  call_number = datanp[1,idx]
  avg_deal_size = datanp[2,idx]
  revenue = datanp[3,idx]

  score = (avg_deal_size * revenue) / call_number

  return score

###Try it out

Let's check Ellen's performance score and print the result.

In [197]:
#Use the calculate performance function to print Ellen's performance
calculate_performance("Ellen")

300.0

###Calculate the performance of each employee
Now you need to calculate the performance score of each employee and add these scores to a list.

📌 Create an empty list "performance_scores" to hold the scores.

📌 Use a for loop to convert the scores into integer type data and append it to the list "sperformance_scores".

In [198]:
#Calculate the performance of each employee
performance_scores = []
for i in names:
  score = int(calculate_performance(i))
  performance_scores.append(score)

print(performance_scores)

[64, 36, 576, 1040, 25, 192, 166, 300, 60, 26, 75]


###Add the scores to the "data" array

Next, you need to add the scores to your "data" array and print the result.

📌 Use the .concatenate() method to add the "performance_scores" list to the "data" array.

In [199]:
#Add the "performance_scores" list to the "data" array
datanp = np.concatenate((datanp, [performance_scores]), axis = 0)

#Print the resulting array
print(datanp)

[[    0     1     2     3     4     5     6     7     8     9    10]
 [  300    10   500    70   100   100   600   800   200   450    80]
 [    8     6    24    32     5    25    25    40    15    10    12]
 [ 2400    60 12000  2275   500   770  4000  6000   800  1200   500]
 [   64    36   576  1040    25   192   166   300    60    26    75]]


###Find out the best and worst performing employees

Finally, you need to determine the best and worst performing employees.

📌 Use the .argmax() and .argmin() methods to find the index of the best and worst performing employees.

In [200]:
#Use .argmax() and .argmin() methods to determine the best and worst performing employees
idx_best_employee = np.argmax(datanp[4])
idx_worst_employee = np.argmin(datanp[4])

#Print out the results
print(f"Best Performing Employee: {names[idx_best_employee]}")
print(f"Worst Performing Employee: {names[idx_worst_employee]}")

Best Performing Employee: Celine
Worst Performing Employee: Sue


##Pandas
The sales department wants to compare the performances of this and last year. Firstly, they delivered your team the performance review from last year. The data is in a comma-separated format, a .csv file called “employee_revenue_lastyear.csv”. It is in tabular form and includes information about 11 employees.

###Importing libraries
First, you need to import the required libraries.

📌 Import the Pandas and NumPy libraries.

In [201]:
#Import Pandas and NumPy
import pandas as pd
import numpy as np

###Get the data from last year
Next, you need to get the data from the .csv file that the sales team provided.

📌 Use the .read_csv() function of the Pandas library to import the data from "employee_revenue_lastyear.csv" and assign it to the variable "last_year".

In [202]:
#Read the data from the "employee_revenue_lastyear.csv" file using the .read_csv() method
last_year = pd.read_csv("employee_revenue_lastyear.csv")

###Check the imported data
It is important to check if everything is included. But you don't need to see the whole DataFrame, it will be enough to see the first and last rows.

📌 Use the .head() function to get the first n-rows of the DataFrame:
  1. Without specifying any number to get the first 5 rows by default.
  2. Give a number n as an argument to print the first n-rows, for example 8.

In [203]:
#Use the .head() function without specifying any number
last_year.head()

Name  Number of Calls  Average Deal Size  Revenue
0    Omer              400                8.0   2000.0
1  Arnold              150               10.0   1000.0
2   Aidan              170               15.0   2000.0
3     Sue              220                5.0   1000.0
4     Ben              140               22.0      NaN

In [204]:
#Use the .head() function with a number n as an argument
last_year.head(8)

Name  Number of Calls  Average Deal Size  Revenue
0    Omer              400                8.0   2000.0
1  Arnold              150               10.0   1000.0
2   Aidan              170               15.0   2000.0
3     Sue              220                5.0   1000.0
4     Ben              140               22.0      NaN
5    Rose              350                8.0   1800.0
6    Lucy               50               12.0    500.0
7   Ellen              560                NaN   3300.0

📌 Use the .tail() function to get the last n-rows of the DataFrame:
  1. Without specifying any number to get the last 5 rows by default.
  2. Give a number n as an argument to print the last n-rows, for example 6.

In [205]:
#Use the .tail() function without specifying any number
last_year.tail()

Name  Number of Calls  Average Deal Size  Revenue
6     Lucy               50               12.0    500.0
7    Ellen              560                NaN   3300.0
8    Karen               20               25.0    500.0
9   Jamaal               30               30.0    800.0
10    Omer              400                8.0   2000.0

In [206]:
#Use the .tail() function with a number n as an argument
last_year.tail(6)

Name  Number of Calls  Average Deal Size  Revenue
5     Rose              350                8.0   1800.0
6     Lucy               50               12.0    500.0
7    Ellen              560                NaN   3300.0
8    Karen               20               25.0    500.0
9   Jamaal               30               30.0    800.0
10    Omer              400                8.0   2000.0

Another way to quickly get the number of rows and columns is using the shape attribute.

📌 Use the *shape* attribute to display the number of rows and columns.

In [207]:
#Use the shape attribute to display the number of rows and columns
last_year.shape

(11, 4)

If you want to get more details about the DataFrame, you can use the .info() function.

📌 Use the .info() function to get more details about the DataFrame.

In [208]:
#Use the .info() function to get more details
last_year.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Name               11 non-null     object 
 1   Number of Calls    11 non-null     int64  
 2   Average Deal Size  10 non-null     float64
 3   Revenue            10 non-null     float64
dtypes: float64(2), int64(1), object(1)
memory usage: 480.0+ bytes


###Add information to the DataFrame
Now you should have enough insights about the DataFrame. :)

You know that the data in the DataFrame is from 2021. This information should be included, so you decide to add the column "Year".

📌 Add the column "Year" to the DataFrame and pass the value "2021" to its rows. Then display the DataFrame to see the result.

In [209]:
#Add the column "Year" and assign the value "2021" to its rows
last_year["Year"] = 2021
#Display the DataFrame
last_year

Name  Number of Calls  Average Deal Size  Revenue  Year
0     Omer              400                8.0   2000.0  2021
1   Arnold              150               10.0   1000.0  2021
2    Aidan              170               15.0   2000.0  2021
3      Sue              220                5.0   1000.0  2021
4      Ben              140               22.0      NaN  2021
5     Rose              350                8.0   1800.0  2021
6     Lucy               50               12.0    500.0  2021
7    Ellen              560                NaN   3300.0  2021
8    Karen               20               25.0    500.0  2021
9   Jamaal               30               30.0    800.0  2021
10    Omer              400                8.0   2000.0  2021

### Get the data from this year

You also need to add the data from this year to be able to compare both years.
You already prepared this data in chapter 4.

Now create a DataFrame using these arrays.

📌 Create a dictionary with the arrays. Specify the column names in the keys.

📌 Convert the dictionary to a Pandas DataFrame "current_year" and use the .head() function to check it.

In [210]:
#Create a dictionary with the column names as keys and the arrays as values
dictionary = {"name": names,
              "calls": call_numbers,
              "avg_deal_size": average_deal_sizes,
              "revenue": revenues}

#Convert the dictionary to a Pandas Dataframe
current_year = pd.DataFrame(dictionary)

#Use the .head() function to check it
current_year.head()

name  calls  avg_deal_size  revenue
0     Ben    300              8     2400
1    Omer     10              6       60
2   Karen    500             24    12000
3  Celine     70             32     2275
4     Sue    100              5      500

Similar to what we did with last year's data, add the year information.

📌 Add the column "Year" to the DataFrame and pass the value "2022" to its rows. Then use the .head() function to see the result.

In [211]:
#Add the column "Year" and assign the value "2022" to its rows
current_year["Year"] = 2022

#Use the .head() function to see the result
current_year.head()

name  calls  avg_deal_size  revenue  Year
0     Ben    300              8     2400  2022
1    Omer     10              6       60  2022
2   Karen    500             24    12000  2022
3  Celine     70             32     2275  2022
4     Sue    100              5      500  2022

###Compare the two DataFrames

Now that you printed the DataFrame "current_year", print "last_year" as well to compare them.

📌 Use the .head() function to print the DataFrame "last_year".

In [212]:
#Use the .head() function to print the DataFrame "last_year"
last_year.head()

Name  Number of Calls  Average Deal Size  Revenue  Year
0    Omer              400                8.0   2000.0  2021
1  Arnold              150               10.0   1000.0  2021
2   Aidan              170               15.0   2000.0  2021
3     Sue              220                5.0   1000.0  2021
4     Ben              140               22.0      NaN  2021

You notice that the column names of the two DataFrames are different. You need to fix this problem.

📌 Assign the column names of "last_year" to "current_year" by using the *columns* attribute.

In [213]:
#Use the columns attribute to assign the column names of "last_year" to "current_year"
current_year.columns = last_year.columns

### Concatenate two DataFrames
Now that the two DataFrames have the same column names, You can merge - or concatenate - them into a single DataFrame "all_data".

📌 Use the .concat() function with the argument "axis" set to 0. Then display the DataFrame.

In [214]:
#Use the .concat() function to concatenate the two DataFrames
all_data = pd.concat([last_year, current_year], axis = 0)

#Display the DataFrame "all_data"
all_data

Name  Number of Calls  Average Deal Size  Revenue  Year
0      Omer              400                8.0   2000.0  2021
1    Arnold              150               10.0   1000.0  2021
2     Aidan              170               15.0   2000.0  2021
3       Sue              220                5.0   1000.0  2021
4       Ben              140               22.0      NaN  2021
5      Rose              350                8.0   1800.0  2021
6      Lucy               50               12.0    500.0  2021
7     Ellen              560                NaN   3300.0  2021
8     Karen               20               25.0    500.0  2021
9    Jamaal               30               30.0    800.0  2021
10     Omer              400                8.0   2000.0  2021
0       Ben              300                8.0   2400.0  2022
1      Omer               10                6.0     60.0  2022
2     Karen              500               24.0  12000.0  2022
3    Celine               70               32.0   2275.0  2022
4       Sue              100                5.0    500.0  2022
5      Bora              100               25.0    770.0  2022
6      Rose              600               25.0   4000.0  2022
7     Ellen              800               40.0   6000.0  2022
8       Bob              200               15.0    800.0  2022
9   Taylor,              450               10.0   1200.0  2022
10     Jude               80               12.0    500.0  2022

###Check the data

This worked out well, but you noticed that the indexes are incorrect. You need to reset them.

📌 Use the .reset_index() function. Set the arguments "drop" and "inplace" to "True". Then display the DataFrame.

In [215]:
#Use the .reset_index() function to reset the indexes
all_data.reset_index(drop = True, inplace = True)

#Display the DataFrame "all_data"
all_data

Name  Number of Calls  Average Deal Size  Revenue  Year
0      Omer              400                8.0   2000.0  2021
1    Arnold              150               10.0   1000.0  2021
2     Aidan              170               15.0   2000.0  2021
3       Sue              220                5.0   1000.0  2021
4       Ben              140               22.0      NaN  2021
5      Rose              350                8.0   1800.0  2021
6      Lucy               50               12.0    500.0  2021
7     Ellen              560                NaN   3300.0  2021
8     Karen               20               25.0    500.0  2021
9    Jamaal               30               30.0    800.0  2021
10     Omer              400                8.0   2000.0  2021
11      Ben              300                8.0   2400.0  2022
12     Omer               10                6.0     60.0  2022
13    Karen              500               24.0  12000.0  2022
14   Celine               70               32.0   2275.0  2022
15      Sue              100                5.0    500.0  2022
16     Bora              100               25.0    770.0  2022
17     Rose              600               25.0   4000.0  2022
18    Ellen              800               40.0   6000.0  2022
19      Bob              200               15.0    800.0  2022
20  Taylor,              450               10.0   1200.0  2022
21     Jude               80               12.0    500.0  2022

Next, you need to check the entries for missing values.

📌 Use the isna.() and .any() function to see if there are missing values in the DataFrame.

In [216]:
#Check the DataFrame for missing values
all_data.isna().any()

Name                 False
Number of Calls      False
Average Deal Size     True
Revenue               True
Year                 False
dtype: bool

From the output, you see that there are missing values in the columns "Average deal size" and "Revenue". You decide to fix this problem by filling the missing values using with the mean of the respective column.

📌 Use the .fillna() function to fill the missing values. Use the .mean() function to set the argument "value" to the mean of "all_data". Again, set "inplace" to "True".

In [249]:
#Replace the missing values with the mean of the respective column
#all_data.fillna(value = np.mean(all_data), inplace = True)

numeric_columns = all_data.select_dtypes(include=[np.number]).columns

for column in numeric_columns:
    column_mean = all_data[column].mean()
    all_data[column].fillna(value=column_mean, inplace=True)

#Display the DataFrame
all_data

Name  Number of Calls  Average Deal Size       Revenue  Year
0      Omer              400           8.000000   2000.000000  2021
1    Arnold              150          10.000000   1000.000000  2021
2     Aidan              170          15.000000   2000.000000  2021
3       Sue              220           5.000000   1000.000000  2021
4       Ben              140          22.000000   2162.142857  2021
5      Rose              350           8.000000   1800.000000  2021
6      Lucy               50          12.000000    500.000000  2021
7     Ellen              560          16.428571   3300.000000  2021
8     Karen               20          25.000000    500.000000  2021
9    Jamaal               30          30.000000    800.000000  2021
10     Omer              400           8.000000   2000.000000  2021
11      Ben              300           8.000000   2400.000000  2022
12     Omer               10           6.000000     60.000000  2022
13    Karen              500          24.000000  12000.000000  2022
14   Celine               70          32.000000   2275.000000  2022
15      Sue              100           5.000000    500.000000  2022
16     Bora              100          25.000000    770.000000  2022
17     Rose              600          25.000000   4000.000000  2022
18    Ellen              800          40.000000   6000.000000  2022
19      Bob              200          15.000000    800.000000  2022
20  Taylor,              450          10.000000   1200.000000  2022
21     Jude               80          12.000000    500.000000  2022

Also, there may be some duplicated rows, you need to drop them.

📌 Use the .drop_duplicates() method to remove any duplicated rows.

📌 Reset the indexes again using the reset_index() function.

In [251]:
#Drop the duplicates
all_data.drop_duplicates(inplace = True)

#Display the DataFrame
all_data

Name  Number of Calls  Average Deal Size       Revenue  Year
0      Omer              400           8.000000   2000.000000  2021
1    Arnold              150          10.000000   1000.000000  2021
2     Aidan              170          15.000000   2000.000000  2021
3       Sue              220           5.000000   1000.000000  2021
4       Ben              140          22.000000   2162.142857  2021
5      Rose              350           8.000000   1800.000000  2021
6      Lucy               50          12.000000    500.000000  2021
7     Ellen              560          16.428571   3300.000000  2021
8     Karen               20          25.000000    500.000000  2021
9    Jamaal               30          30.000000    800.000000  2021
11      Ben              300           8.000000   2400.000000  2022
12     Omer               10           6.000000     60.000000  2022
13    Karen              500          24.000000  12000.000000  2022
14   Celine               70          32.000000   2275.000000  2022
15      Sue              100           5.000000    500.000000  2022
16     Bora              100          25.000000    770.000000  2022
17     Rose              600          25.000000   4000.000000  2022
18    Ellen              800          40.000000   6000.000000  2022
19      Bob              200          15.000000    800.000000  2022
20  Taylor,              450          10.000000   1200.000000  2022
21     Jude               80          12.000000    500.000000  2022

In [252]:
#Reset the indexes
all_data.reset_index(drop = True, inplace = True)

#Display the DataFrame
all_data

Name  Number of Calls  Average Deal Size       Revenue  Year
0      Omer              400           8.000000   2000.000000  2021
1    Arnold              150          10.000000   1000.000000  2021
2     Aidan              170          15.000000   2000.000000  2021
3       Sue              220           5.000000   1000.000000  2021
4       Ben              140          22.000000   2162.142857  2021
5      Rose              350           8.000000   1800.000000  2021
6      Lucy               50          12.000000    500.000000  2021
7     Ellen              560          16.428571   3300.000000  2021
8     Karen               20          25.000000    500.000000  2021
9    Jamaal               30          30.000000    800.000000  2021
10      Ben              300           8.000000   2400.000000  2022
11     Omer               10           6.000000     60.000000  2022
12    Karen              500          24.000000  12000.000000  2022
13   Celine               70          32.000000   2275.000000  2022
14      Sue              100           5.000000    500.000000  2022
15     Bora              100          25.000000    770.000000  2022
16     Rose              600          25.000000   4000.000000  2022
17    Ellen              800          40.000000   6000.000000  2022
18      Bob              200          15.000000    800.000000  2022
19  Taylor,              450          10.000000   1200.000000  2022
20     Jude               80          12.000000    500.000000  2022

### Data analysis
#### Statistical analysis
The DataFrame is ready, great!

Now you can use it to analyse the overall performance of the employees over the last two years. You prepare a summary of the statistics.

📌 Use the .describe() method.

In [254]:
#Use the .descrbe() method to get a summary of the statistics
all_data.describe()

Number of Calls  Average Deal Size       Revenue         Year
count        21.000000          21.000000     21.000000    21.000000
mean        252.380952          16.829932   2169.863946  2021.523810
std         223.112186           9.991794   2656.901262     0.511766
min          10.000000           5.000000     60.000000  2021.000000
25%          80.000000           8.000000    770.000000  2021.000000
50%         170.000000          15.000000   1200.000000  2022.000000
75%         400.000000          25.000000   2275.000000  2022.000000
max         800.000000          40.000000  12000.000000  2022.000000

You can do the same for each year separately.

📌 Prepare a summary of the statistics for the data from 2021.

📌 Prepare a summary of the statistics for the data from 2022.

In [256]:
#Use the .descrbe() method to get a summary of the statistics for 2021
all_data[all_data["Year"] == 2021].describe()

Number of Calls  Average Deal Size      Revenue    Year
count        10.000000          10.000000    10.000000    10.0
mean        209.000000          15.142857  1506.214286  2021.0
std         177.165961           8.218115   898.025426     0.0
min          20.000000           5.000000   500.000000  2021.0
25%          72.500000           8.500000   850.000000  2021.0
50%         160.000000          13.500000  1400.000000  2021.0
75%         317.500000          20.607143  2000.000000  2021.0
max         560.000000          30.000000  3300.000000  2021.0

In [257]:
#Use the .descrbe() method to get a summary of the statistics for 2022
all_data[all_data["Year"] == 2022].describe()

Number of Calls  Average Deal Size       Revenue    Year
count        11.000000          11.000000     11.000000    11.0
mean        291.818182          18.363636   2773.181818  2022.0
std         260.223680          11.552253   3542.826748     0.0
min          10.000000           5.000000     60.000000  2022.0
25%          90.000000           9.000000    635.000000  2022.0
50%         200.000000          15.000000   1200.000000  2022.0
75%         475.000000          25.000000   3200.000000  2022.0
max         800.000000          40.000000  12000.000000  2022.0

#### Ranking of the employees by revenue
You also want to rank the employees by the generated revenue.

📌 Use the .sort_values() method to sort the values by the column “Revenue”.

In [258]:
#Sort the DataFrame by the column "Revenue"
all_data.sort_values(by = "Revenue")

Name  Number of Calls  Average Deal Size       Revenue  Year
11     Omer               10           6.000000     60.000000  2022
20     Jude               80          12.000000    500.000000  2022
6      Lucy               50          12.000000    500.000000  2021
14      Sue              100           5.000000    500.000000  2022
8     Karen               20          25.000000    500.000000  2021
15     Bora              100          25.000000    770.000000  2022
18      Bob              200          15.000000    800.000000  2022
9    Jamaal               30          30.000000    800.000000  2021
1    Arnold              150          10.000000   1000.000000  2021
3       Sue              220           5.000000   1000.000000  2021
19  Taylor,              450          10.000000   1200.000000  2022
5      Rose              350           8.000000   1800.000000  2021
0      Omer              400           8.000000   2000.000000  2021
2     Aidan              170          15.000000   2000.000000  2021
4       Ben              140          22.000000   2162.142857  2021
13   Celine               70          32.000000   2275.000000  2022
10      Ben              300           8.000000   2400.000000  2022
7     Ellen              560          16.428571   3300.000000  2021
16     Rose              600          25.000000   4000.000000  2022
17    Ellen              800          40.000000   6000.000000  2022
12    Karen              500          24.000000  12000.000000  2022

As you did with the .describe() function, you can also use conditions to filter information.

📌 Sort the revenue values of 2022.

In [259]:
#Sort the revenue values od 2022
all_data[all_data["Year"] == 2022].sort_values(by = "Revenue")

Name  Number of Calls  Average Deal Size  Revenue  Year
11     Omer               10                6.0     60.0  2022
14      Sue              100                5.0    500.0  2022
20     Jude               80               12.0    500.0  2022
15     Bora              100               25.0    770.0  2022
18      Bob              200               15.0    800.0  2022
19  Taylor,              450               10.0   1200.0  2022
13   Celine               70               32.0   2275.0  2022
10      Ben              300                8.0   2400.0  2022
16     Rose              600               25.0   4000.0  2022
17    Ellen              800               40.0   6000.0  2022
12    Karen              500               24.0  12000.0  2022

#### How many years of employment?

Finally, you can count how many times an employee appears in the DataFrame to determine which employee has worked for the company for two years.

📌 Use the value_counts() function for the column "Name".

In [260]:
#Count how often the names of the employees appear in the DataFrame
all_data["Name"].value_counts()

Name
Omer       2
Sue        2
Ben        2
Rose       2
Ellen      2
Karen      2
Arnold     1
Aidan      1
Lucy       1
Jamaal     1
Celine     1
Bora       1
Bob        1
Taylor,    1
Jude       1
Name: count, dtype: int64